### ISSUE TITLE
-uninstall left LuLu helper installed

### ISSUE THREAD

**Issue by maxxer** [objective-see/LuLu#14]
I ran the uninstall but I found the *LuLu helper* application was still present on my computer

**Comment by simonrosted** [comment]
This is solved by running the configure.sh uninstall script outside its default folder, that otherwise contains Lulu.app on default.

The issue is that if you run "sudo configure.sh -uninstall" in the same folder that contains the Lulu.app, then the Lulu Helper app is launched from that local folder immediately after running the uninstall script.

**Comment by objective-see** [comment]
Thanks for reporting! The new UI-based installer/uninstaller (and [`configure.sh`](https://github.com/objective-see/LuLu/blob/master/configure/Configure/Script/configure.sh) script) should now fully remove all LuLu components on an uninstall :)
