### ISSUE TITLE
Add preference for hiding Dock icon

### ISSUE THREAD

**Issue by bkazez** [objective-see/LuLu#212]

**Comment by ldexterldesign** [comment]
Hi,

This setting exists in macOS preferences

If you're on another platform then be more descriptive

<img width="712" alt="Screenshot 2020-10-02 at 01 33 54" src="https://user-images.githubusercontent.com/1715809/94876360-5af70e00-044f-11eb-8a37-c7272e93f01f.png">

Sincerely

**Comment by bkazez** [comment]
1. Click menu bar > Preferences
2. Lulu icon appears in the Dock

It seems more standard for status bar items not to show the Dock icon in this case.

**Comment by objective-see** [comment]
By design, when activated (i.e. an alert is shown, the user open the Rules/Prefs window, etc), LuLu will have a dock icon...this allows the user toggle between other apps, then come back to it via command+tab, etc. 

When the visible window(s) are closed, LuLu will automatically return to the background (w/ no active dock icon). 

Most of the other status bar apps installed on my computer, follow this same approach.
