### ISSUE TITLE
2.0: Apps requesting connection to 192.168.1.1 keep repeating dialog

### ISSUE THREAD

**Issue by jguerin** [objective-see/LuLu#235]
I've had this happen on NordVPN and Remote Desktop now:
![image](https://user-images.githubusercontent.com/1470655/95660395-6647da80-0adc-11eb-9c7c-5a91132d0307.png)

I have to dismiss the dialog to get it to stop.

**Comment by pwardle** [comment]
This is is expected behavior ...when an/any apps makes a DNS request.

You can either approve each app, or simply created a global rule, setting `Program Path` to "*" and `Remote Port` to 53:
![image](https://user-images.githubusercontent.com/36903521/97538385-62350d00-1964-11eb-8de5-c90e54d793b8.png)

**Comment by jguerin** [comment]
Awesome, thanks for clarifying! I was wondering if it was because I had a VPN app set up :)
