### ISSUE TITLE
Can't connect to custom VPN using VPN Monitor with LuLu 2.0.0 enabled MacOS Catalina 10.15.3

### ISSUE THREAD

**Issue by feewet** [objective-see/LuLu#281]
With LuLu enabled, I can't connect to my VPN using VPN Monitor on MacOS Catalina 10.15.3.  https://www.vpnmonitor.eu/ 

Using NordVPN works fine, but with VPN Monitor and a custom VPN IP I get the following error: "The L2TP-VPN server did not respond. Try reconnecting."

I tried whitelisting VPN monitor but it still won't work, and LuLu does not give the usual notification to whitelist a new application. Any thoughts?

**Comment by ptiLuc** [comment]
Same problem here with a Cisco IPsec VPN for accessing my Lab environment.

**Comment by objective-see** [comment]
This was an Apple bug ...that impacted any products leveraging Network Extensions (LuLu, Little Snitch etc.)

From the developers of Little Snitch: 
"_There is a bug in macOS Big Sur 11.0.1 where VPNs of type Cisco IPSec won’t work when a Network Extension is installed. This affects Little Snitch 5 (not older versions!) and many other products based on Network Extensions. The VPN will connect successfully, but no data is transferred. The bug has been reported to Apple and will be fixed in macOS 11.1_"

Good news, Apple has fixed it in macOS 11.1

For more details see: https://www.obdev.at/support/littlesnitch/245917044280819
