### ISSUE TITLE
Instructions on how to compile

### ISSUE THREAD

**Issue by adamretter** [objective-see/LuLu#35]
For those of us who are developers but are not familiar with XCode or Objective-C, it is not obvious at all how to compile LuLu. I have tried and failed!

Could you provide some instructions please?

**Comment by alvarnell** [comment]
It's really not necessary to compile it. Just download the current LuLu_x.x.x.zip file from the [Releases page](https://github.com/objective-see/LuLu/releases) then execute the configuration script (configure.sh) with the -install flag, as root: 

> sudo ./configure.sh -install

**Comment by adamretter** [comment]
@alvarnell Sure but the point of open source is to be able to compile from source, and potentially contribute changes. So I would appreciate the guidance still...

**Comment by alvarnell** [comment]
That's fair, but since you have already said you are not familiar with Xcode or Objective-C, I would have to seriously question your ability to contribute any changes. Compiling is actually pretty simple, but establishing a branch with recommended changes requires some serious coding knowledge.

**Comment by pronouncedJerry** [comment]
the instructions also say to type out "$ sudo configure.sh -install" when it's really "$ sudo ./configure.sh -install"

**Comment by adamretter** [comment]
@alvarnell I guess your not open to contributions, so I won't waste my time further

**Comment by alvarnell** [comment]
Adam,

Not sure why you are addressing this to me? 

I'm sure Patrick, the developer would welcome any and all code contributions from qualified programmers, and by written enhancement suggestions from non-programmers like you and I.

-Al-

**Comment by mischievous** [comment]
@adamretter if you still want help I will be happy to try and walk you thought it.  From my POV the project is a mess.  Just let me know.

**Comment by mischievous** [comment]
BTW more IDES have "special" quarks that are not obvious to people coming from different IDES,  If someone if familiar with C/C++, Objective-C is not that hard to pick up.  Just from my quick look at the code I see lots of "not standard" practices in the current code base.

**Comment by mischievous** [comment]
If you check out my fork and open the Lulu.xcodeproj (NOT THE lulu.xcworkspace) in xcode 9.2.x.  Make sure to select the "Lulu" target from the toolbar area.  Hit the build button and it should build.  

I moved the code into one xcode project so that its easier to work with.  No special copy functions.  Proper target dependancies (why it build everything from the "Lulu" target).  Easier to configure the OSX sdk being used.  Too many more to actually list here.  

I have not yet verified it will actually work.  I still need to audit the code to remove other things I really dislike.    

Let me know if you have any problems.
