### ISSUE TITLE
MacOS 12 - no way to uninstall or upgrade Lulu

### ISSUE THREAD

**Issue by shynepo** [objective-see/LuLu#391]
error: upgrade failed 

<img width="503" alt="Bildschirmfoto 2021-07-29 um 22 05 28" src="https://user-images.githubusercontent.com/80540014/127542985-6d5c2e4f-d811-4d51-90ca-91e9d1394bfc.png">

or error: unintsall failed

I am using a M1 Macbook air. Mac OS 12 is running on this machine. I am not sure that this is the problem... I think the problem might be, that I had Lulu installed before  (on other macbook, no M1, MacOs 10 I guess) and the old backup screwed things up. So, what can I do to remove all the leftovers of the old "Lulu"? Maybe then the installation will proceed.

**Comment by shynepo** [comment]
I found the solution, I think:

https://github.com/objective-see/LuLu/issues/208#issuecomment-699732106
https://github.com/objective-see/LuLu/issues/208#issuecomment-699844394

MacOS 12 is the "problem". It won't install because I have the wrong OS number (probably).
Too bad I don't know what to do to make it work :D
For developers is must be easy....

**Comment by shynepo** [comment]
Hola :) Anybody here in the desert? I'd love to save me the time of installing Big Sur if the problem is only the upfront checking of the MacOs Version. Any solution? I do not know how to change that and "compile" the programme. Just no idea :(

**Comment by shynepo** [comment]
♪ ♫  #  ♪ ♫  # ♪ ♫
_I need somebody
(Help!) not just anybody
(Help!) you know I need someone
Help!
I never needed anybody's help in any way
But now these days are gone, I'm not so self assured (but now these days are gone)
(And now I find) Now I find I've changed my mind and opened up the doors
Help me if you can, I'm feeling down
And I do appreciate you being 'round
Help me get my feet back on the ground
Won't you please, please help me?_

**Comment by tonyxiao** [comment]
Still getting this issue, on latest version of Lulu

**Comment by shynepo** [comment]
Its the OS version... You have to downgrade.

**Comment by objective-see** [comment]
@shynepo, thanks for your patience! I was literally in the desert (for BlackHat/DefCon)
The latest version should address this issue: https://github.com/objective-see/LuLu/releases/tag/v2.3.2

...if issue w/ macOS 12/Monterey still persist, please lmk!

**Comment by shynepo** [comment]
Thank you, I am on Big Sur again :)

**Comment by amplicity** [comment]
I am still having this issue, also wrote into bugs@objective-see.com

I had 1.2.3 on macOs mojave. I recently bought a mac m1 with monterey. I time machine'd from mojave -> monterey, and am unable to uninstall, upgrade, or access the internet (except when in safe mode).

I tried:
- allowed insecure access from the mac recovery menu
- terminated all processes in activity monitor that mention 'lulu'
- downloaded 2.3.2 and attempted to uninstall or upgrade, but both fail

At this point, I just need to completely remove lulu. Is there anyway to manually remove LuLu without going through the uninstall dialog?

**Comment by bwilli66** [comment]
I had this same issue and was able to fix it with some trial and error. Perhaps this helps anyone still having this issue. 

I had originally installed v1.2.3 on my MacBook on macOS Catalina and I don't think I've upgraded since. I recently upgraded to Monterey noticed that LuLu wasn't working and perhaps hadn't been working for a while.

In an effort to remove and re-install LuLu, I tried uninstalling it using AppZapper (bad idea, I know) which left my installation in a strange, removed-but-not-officially-uninstalled state. 

I then downloaded and installed version 2.4.1 and was not able to "uninstall" or "upgrade", both of which gave me the same type of error this issue was opened against. 
I tried downloading/installing an older version of LuLu (v2.2.0) and using that to uninstall and again got the same error. 
I tried installing the original version (v1.2.3) that I installed back in 2020, that also didn't work. 

I then tried running "brew install lulu" from my terminal. When running this command it first updated my HomeBrew because mine was pretty out-of-date and then installed v2.4.1. After that, everything worked great.  

Hope this helps.
