### ISSUE TITLE
incorrect "LuLu's Network Extension is Not Running" message, cannot open 

### ISSUE THREAD

**Issue by apfrod** [objective-see/LuLu#486]
macOS 12.5.1
LuLu 2.4.2

After reinstalling and recovering from Time Machine, then having to re-upgrade to Monterey, my mac is in a weird state.

When trying to launch LuLu I get the message "LuLu's Network Extension is Not Running"
<img width="260" alt="Screenshot 2022-08-30 at 12 29 40" src="https://user-images.githubusercontent.com/1449068/187425556-44fb16e2-27c1-4bb1-bd26-c7bab21672e0.png">

however running `systemextensionsctl list` shows:
```
enabled	active	teamID	bundleID (version)	name	[state]
*	*	VBG97UB4TA	com.objective-see.lulu.extension (2.4.2/2.4.2)	Extension	[activated enabled]
```

LuLu appears in Activity Monitor so appears to be running, but I cannot see the config or run the uninstaller. Do I have to disable SIP to uninstall this extension so I can re-install cleanly?

**Comment by jebediah2** [comment]
Same here. Did you figure it out?

**Comment by Mertonoia** [comment]
Same issue here after Quitting LuLu for less than a day. Very eager to get her back up and running.

**Comment by MacHadis379** [comment]
Thank you for posting solution to  this problem.

**Comment by apfrod** [comment]
It worked for me

**Comment by dnut** [comment]
> It worked for me

That's wonderful, but the bug is still not fixed. Users should not need to uninstall and reinstall an application to make it work properly. I would reopen this issue to represent the fact that the bug still exists. You can un-watch the issue if you're not interested in seeing any updates.

**Comment by 3ftomi** [comment]
> > It worked for me
> 
> That's wonderful, but the bug is still not fixed. Users should not need to uninstall and reinstall an application to make it work properly. I would reopen this issue to represent the fact that the bug still exists. You can un-watch the issue if you're not interested in seeing any updates.

First of all it's not a bug but a security feature of the OS.
You don't nee to reinstall, just to approve it as the popup asks (in the System Preferences/Security & Privacy/General tab at the right lower corner).

**Comment by dnut** [comment]
> First of all it's not a bug 

It absolutely is a bug if the application communicates false statements to the user.

>  You don't nee to reinstall, just to approve it as the popup asks (in the System Preferences/Security & Privacy/General tab at the right lower corner).

I'm sure there is some*scenario where that is the correct mitigation when you see this popup. But this popup also appears even when that area of system settings does not show anything about lulu's network extension.

**Comment by 3vidar** [comment]
> if you miss the promote message, you can turn the Network Extension manually. and here is where Network Extension is. System settings --> General --> Login Items & Extension --> (scroll down) Extensions --> Network Extensions --> by click the right side of the Network Extension "!" sign. then network extension window will open, you can find the lulu list in there, turn on it, everything will be ok.

Thats the correct solution, thank you!

**Comment by williegagnon** [comment]
Ce n’est donc pas « Security & Privacy System Preferences », comme c’est écrit dans l’image.

**Comment by colinbrislawn** [comment]
<img width="707" alt="Screenshot 2024-10-09 at 10 14 29 PM" src="https://github.com/user-attachments/assets/384bf6f2-83ba-4f34-a928-a7cc88e295bb">

<img width="701" alt="Screenshot 2024-10-09 at 10 16 24 PM" src="https://github.com/user-attachments/assets/1abae748-aeed-4e55-bbfc-805c873c65f0">

It sounds like this may be due to changes in OSX 15
I'm hopeful they can streamline this for future users!

**Comment by sharadbharsakal1** [comment]
In Login Items & Extensions u ll find Lulu just allow Lulu and you can easily access Lulu after restart

**Comment by andrewonyango** [comment]
the extension is active and enabled

for me, it's not a result of an upgrade as i already had Tahoe when i first installed Lulu, and i have been using it (quite happily) for what it's supposed to do, but if i can't get it to work, i'll have to move on to something else

thanks to the devs, anyway

<img width="864" height="522" alt="Image" src="https://github.com/user-attachments/assets/caa38aed-154d-4503-b4e7-8ff09161ee14" />

<img width="1351" height="67" alt="Image" src="https://github.com/user-attachments/assets/a2363972-2833-4429-89fd-f73fb3ca277d" />

(i should add that i've tried the remedies mentioned here--except deleting/uninstalling as of now, since once i do that, it's a one-way trip--in addition to killing it from Activity Monitor and restarting the app, toggling the extension on and off, etc...and any such combinations)
