### ISSUE TITLE
question - how does lulu know url

### ISSUE THREAD

**Issue by SynapseScribe** [objective-see/LuLu#539]
how does lulu know the url an app is connecting to? is it intercepting https traffic to be able to know what's after first slash after the domain? if so, does it add a certificate in the trusted authorities and perform some kind of mitm or does apple's new network extension framework simply allow this kind of monitoring?

also is there any windows firewall that is able to see the url in similar manner?

**Comment by mdjunior** [comment]
Hi,

In the LuLu documentation there is mention of "Due to limitations of macOS, blocking via host name is only applicable to (as Apple notes) "Network.framework or NSURLSession connections"." So the simple answer is that Apple provides this capability and LuLu is using a framework provided by Apple itself to provide this functionality (more information is available [here](https://developer.apple.com/documentation/networkextension?language=objc)).

There are other older versions of Lulu that used other functionality, here I am only talking about version 2.5.0.

When using this way, once Lulu's Network Extension is active, it starts to receive network events/flows and apply "verdicts" to them, saying whether they can be allowed or not. More technically, [here](https://developer.apple.com/documentation/networkextension/content_filter_providers?language=objc) it talks about content filters and [here](https://developer.apple.com/documentation/networkextension/nefilterflow?language=objc) about data structure of events/flows. [In this file](https://github.com/objective-see/LuLu/blob/50478cdea08e2e6c1fae935890938eb173aa146b/LuLu/Extension/FilterDataProvider.m#L132), here we have the function that processes the receipt of a new flow.

That is, LuLu is not "intercepting" traffic, it is just using a system functionality and inside the flow comes the complete information of the URL being accessed. But the system is not always able to provide this complete URL, as there are different ways in the operating system to gain access to the network. When programs use Apple-supplied libraries like `URLSession`, the full URL comes within flow. Now if you use something different, this information will not be available within flow (only the destination IP and port).

By observing the logs in LuLu's debug mode (`log stream --level debug --predicate="subsystem='com.objective-see.lulu'"`), you can analyze how the flows are received by network extension (the URL field is only printed in this log [here](https://github.com/objective-see/LuLu/blob/50478cdea08e2e6c1fae935890938eb173aa146b/LuLu/Extension/FilterDataProvider.m#L187)). Next I'm putting the log of an event with the URL (using the `URLSession` library) and another using another program.

Using `URLSession`:
```
com.objective-see.lulu.extension: [com.objective-see.lulu:extension] remote endpoint: 127.0.0.3:80 / url: http://lulu-2r.example.org/v1/configs
```

Another access (`/usr/bin/perl -MHTTP::Tiny -e 'print HTTP::Tiny->new->get(q{http://ifconfig.me/all.json})->{content}'`):
```
com.objective-see.lulu.extension: [com.objective-see.lulu:extension] remote endpoint: 34.160.111.145:80 / url: (null)
```

Unfortunately I don't know how the Windows APIs work and if they provide capabilities to inspect complete URLs, but the native windows firewall already provides the ability to control access per application.

**Comment by kandraPravallika** [comment]
which algorithm does lulu is using means what is the backend logic of the lulu firewall?how it filters the blocked list?
