### ISSUE TITLE
Installer requests restart, restarts are for kernel upgrades

### ISSUE THREAD

**Issue by rjzak** [objective-see/LuLu#56]
It seems to me that the installer ought to be able to:
- unload the old LuLu module (`/sbin/kextunload`), if present;
- install the new LuLu module;
- load the new module into kernel memory (`/sbin/kextload`); and finally,
- restart the LuLu application in user space.

A restart of the machine should not be required. I did notice though that trying to unload the module isn't possible, the kernel says the services failed to terminate. Is this intentional?

**Comment by objective-see** [comment]
I equally dislike restarts - but it appears necessary :(

When a Network Kernel Extension (NKE) registers various socket filters (via `sflt_register`), these get 'attached' to any new socket that is created - allowing the firewall to 'filter' on network events. 

AFAIK (and my testing seem to confirm) the issue is, the OS, by design, does not detach the attached socket filter from a socket until that socket (which the firewall does not create/or 'own') is closed - even if the firewall calls `sflt_unregister`. 

So if the kernel extension get's unloaded, and an existing socket is still around (from any process) when that socket does anything (i.e. send data), the OS will still try to call into the now unloaded kext - and this good b00m; panic. This is why (by design) the LuLu kext prevents itself from being unloaded by a user.  

Thus is seems the only safe way to unload the kext is to unregister everything, then let the OS handle the unload during shutdown. I'll look into this more though, as yes, agreed, that not requiring a reboot would be nice!

Other (similar) firewall products requires a reboot, likely for this same reason too

**Comment by rjzak** [comment]
Great explanation, makes sense.

**Comment by alvarnell** [comment]
I'll just add that a restart is required for Little Snitch updates, as well.
