### ISSUE TITLE
Duplicate rule...

### ISSUE THREAD

**Issue by MrAtheist** [objective-see/LuLu#601]
Lulu v2.6.3

Lets say I modified to a specific port instead of `any port` for a process...

<img width="1010" alt="Screenshot 2024-04-10 at 14 26 53" src="https://github.com/objective-see/LuLu/assets/4513916/ab1d2eb0-5053-4cb3-bec4-5a0f7d18d4c1">

BUT after a while the original rule is added back automagically with `any port`... is this by design or is there a way to disable this behavior? basically this defeats the whole purpose of using this tool...

<img width="1010" alt="Screenshot 2024-04-10 at 14 06 01" src="https://github.com/objective-see/LuLu/assets/4513916/a0a817d6-39c2-40e6-adef-39fb3947c877">

**Comment by objective-see** [comment]
I'm guessing this is because, `Allow Apple Programs` is enabled? 

<img width="584" alt="image" src="https://github.com/objective-see/LuLu/assets/11327812/70a06a91-247d-4d39-8c9e-db8be03063be">

....so when `parsecd` attempts to connect, LuLu see's that setting is enabled and adds the "any address / any port" rule. 

However, yes I agree this is not ideal (sure you could turn off `Allow Apple Programs`, but that's a nice setting to make sure one is not inundated with alerts when normal OS stuff connects out, as expected).

What do you think if the current logic is changed as following: 
With `Allow Apple Programs` enabled, will automatically add a rule for any Apple process (which is what happens now), **unless**, the user has specified a more specific rule? 

...thoughts?

**Comment by MrAtheist** [comment]
I see, alternatively i just set it to "blocked" for "any port" specifically, and it seems like the rule is respected / not overwritten as far as i can tell...

I think thats much less hassle then tweaking the logic, closing this issue... thanks!

<img width="1010" alt="image" src="https://github.com/objective-see/LuLu/assets/4513916/25ddcf9d-bf19-41fa-b609-030d97b2197b">
